services:
  db:
    image: postgres:15-alpine
    container_name: alsultan-db
    environment:
      POSTGRES_USER: alsultan
      POSTGRES_PASSWORD: Awe@93554
      POSTGRES_DB: alsultan_bakery
    ports:
     - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alsultan -d alsultan_bakery"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  alsultan-bakery:
    build: .
    container_name: alsultan-bakery
    environment:
      DATABASE_URL: postgresql://alsultan:Awe@93554@db:5432/alsultan_bakery
      PORT: "3000"
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "3020:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data:
